// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrderByUuid implements cancelOrderByUuid operation.
	//
	// Отменяет существующий заказ.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrderByUuid(ctx context.Context, params CancelOrderByUuidParams) (CancelOrderByUuidRes, error)
	// CreateOrder implements createOrder operation.
	//
	// Создает новый заказ.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrderByUuid implements getOrderByUuid operation.
	//
	// Получает заказ по его UUID.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByUuid(ctx context.Context, params GetOrderByUuidParams) (GetOrderByUuidRes, error)
	// PayOrder implements payOrder operation.
	//
	// Оплачивает существующий заказ.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (PayOrderRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
