// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderByUuidOperation OperationName = "CancelOrderByUuid"
	CreateOrderOperation       OperationName = "CreateOrder"
	GetOrderByUuidOperation    OperationName = "GetOrderByUuid"
	PayOrderOperation          OperationName = "PayOrder"
)
