services: # Здесь описываются контейнеры, необходимые для Inventory-сервиса

  mongo-inventory: # Контейнер с MongoDB — используется для хранения данных об инвентаре (например, запчасти, компоненты)
    image: ${MONGO_IMAGE_NAME}
    # Образ MongoDB задаётся через переменную окружения MONGO_IMAGE_NAME — удобно управлять версией из .env файла
    # Пример: MONGO_IMAGE_NAME=mongo:7.0.5

    container_name: mongo-inventory
    # Устанавливаем удобное читаемое имя контейнера — пригодится для логов и отладки

    env_file:
      - .env

    volumes:
      - mongo_inventory_data:/data/db
      # Подключаем локальный Docker-том к директории MongoDB, где хранятся все данные (коллекции, документы и т.д.)
      # Это нужно для сохранения данных между перезапусками контейнера

    ports:
      - "${EXTERNAL_MONGO_PORT}:27017"
      # Пробрасываем внутренний порт MongoDB (27017) наружу на порт, указанный в переменной INVENTORY_MONGO_PORT
      # Это позволяет подключаться к Mongo из других контейнеров и внешних инструментов (например, Mongo Compass)

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh --quiet -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase ${MONGO_AUTH_DB}",
        ]
      # Проверка готовности MongoDB: выполняем команду ping через mongosh с указанием логина и пароля
      # --quiet отключает лишний вывод, чтобы результатом был только "1" при успехе
      interval: 10s # Запускаем проверку каждые 10 секунд
      timeout: 5s # Максимальное время ожидания выполнения ping-команды
      retries: 5 # После 5 неудачных проверок подряд контейнер считается "неработоспособным"

    restart: unless-stopped
    # Автоматически перезапускаем контейнер, если он аварийно завершился
    # Но если мы остановим его вручную — он не запустится повторно

    networks:
      - microservices-net
      # Подключаем контейнер к общей сети всех микросервисов, чтобы они могли взаимодействовать между собой по имени

volumes: # Раздел с томами — определяем хранилище, которое создаст Docker
  mongo_inventory_data:
  # Именованный том, в котором будут храниться данные MongoDB для Inventory-сервиса
  # Он живёт отдельно от контейнера и сохраняется даже после удаления контейнера

networks: # Определение используемой сети
  microservices-net:
    external: true
    # Мы не создаём новую сеть, а подключаемся к внешней, общей для всех микросервисов
    # Её должен создать docker-compose.yml или вручную: docker network create microservices-net