name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint Go code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.2.1
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: golangci-lint
      run: |
        golangci-lint run inventory/...
        golangci-lint run order/...
        golangci-lint run payment/...
        golangci-lint run shared/...

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Run tests
      run: |
        cd order && go test ./...
        cd ../inventory && go test ./...
        cd ../payment && go test ./...
        cd ../shared && go test ./...

  build:
    name: Build all services
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Build services
      run: |
        cd order && go build ./cmd/main.go
        cd ../inventory && go build ./cmd/main.go
        cd ../payment && go build ./cmd/main.go 